#!/usr/bin/env python3
import json
from pathlib import Path

CATALOG = Path(__file__).parent / "FreeTube" / "FreeTube" / "Localizable.xcstrings"

# Simplified Chinese translations for the user-facing FreeTube UI.
# Missing keys are created so newly added SwiftUI strings can also be localized.
ZH = {
    "About": "关于",
    "Account": "账号",
    "Add to favorites": "添加到收藏",
    "Remove from favorites": "从收藏中移除",
    "Add to playlist": "添加到播放列表",
    "All videos": "全部视频",
    "Allow cellular data": "允许使用蜂窝数据",
    "Already at latest (%@)": "已是最新版本（%@）",
    "Autoplay next video": "自动播放下一个视频",
    "Cache limit": "缓存上限",
    "Cancel": "取消",
    "Cancel selection": "取消选择",
    "Channel": "频道",
    "Channels": "频道",
    "Channels and videos you've watched": "你观看过的频道和视频",
    "Channels you follow": "你关注的频道",
    "Channels you subscribe to on YouTube will show up here.": "你在 YouTube 订阅的频道会显示在这里。",
    "Clear": "清除",
    "Clear all": "全部清除",
    "Close": "关闭",
    "Comments": "评论",
    "Completed": "已完成",
    "Convert": "转换",
    "Convert audio to MP3": "将音频转换为 MP3",
    "Convert video to H.264": "将视频转换为 H.264",
    "Cookies are stored only in the Keychain.": "Cookie 仅保存在钥匙串中。",
    "Copy URL": "复制链接",
    "Copy URL at current time": "复制当前时间点链接",
    "Couldn't load video": "无法加载视频",
    "Couldn't read this link": "无法读取此链接",
    "Couldn't load the video stream.": "无法加载视频流。",
    "Couldn't read YouTube's response.": "无法读取 YouTube 的响应。",
    "Create": "创建",
    "Create new playlist": "新建播放列表",
    "Creator": "创作者",
    "Date downloaded": "下载日期",
    "Delete": "删除",
    "Delete from downloaded": "从下载中删除",
    "Delete this video?": "删除这个视频？",
    "Deselect all": "取消全选",
    "Diagnostics": "诊断",
    "Done": "完成",
    "Download": "下载",
    "Downloaded": "已下载",
    "Downloading": "正在下载",
    "Downloads": "下载",
    "Duration": "时长",
    "Edit": "编辑",
    "Favorites": "收藏",
    "Fetch": "解析",
    "File size": "文件大小",
    "History": "历史记录",
    "Home": "首页",
    "Library": "资料库",
    "Liked videos": "喜欢的视频",
    "Link": "链接",
    "Loading…": "加载中…",
    "Never": "从未",
    "Next": "下一个",
    "No channel detected": "未检测到频道",
    "No downloads": "暂无下载",
    "No playlists": "暂无播放列表",
    "Not yet loaded": "尚未加载",
    "Nothing here yet": "这里暂时没有内容",
    "Open in browser": "在浏览器中打开",
    "Open in…": "打开方式…",
    "Parallel fragments": "并行分片",
    "Paste a link…": "粘贴链接…",
    "Paused": "已暂停",
    "Playback": "播放",
    "Playlists": "播放列表",
    "Preferred quality": "首选画质",
    "Prefetch next video": "预加载下一个视频",
    "Preparing…": "正在准备…",
    "Processing…": "正在处理…",
    "Queued": "排队中",
    "Ready": "就绪",
    "Recent": "最近",
    "Recent searches": "最近搜索",
    "Refresh": "刷新",
    "Remove": "移除",
    "Reset": "重置",
    "Reset session": "重置会话",
    "Reset session?": "重置会话？",
    "Restricted search mode": "受限搜索模式",
    "Retry": "重试",
    "Save": "保存",
    "Save logs to file": "将日志保存到文件",
    "Saved on device": "已保存在设备上",
    "Search": "搜索",
    "Search YouTube": "搜索 YouTube",
    "Select": "选择",
    "Select all": "全选",
    "Settings": "设置",
    "Share": "分享",
    "Share latest log…": "分享最新日志…",
    "Show log folder": "显示日志文件夹",
    "Sign in": "登录",
    "Sign in to YouTube": "登录 YouTube",
    "Sign out": "退出登录",
    "Sort by": "排序方式",
    "Subscribe": "订阅",
    "Subscribed": "已订阅",
    "Subscriptions": "订阅内容",
    "Title": "标题",
    "Transfer queue": "传输队列",
    "Troubleshooting": "故障排查",
    "Unsubscribe": "取消订阅",
    "Update now": "立即更新",
    "Version": "版本",
    "Video": "视频",
    "Videos": "视频",
    "Watch history": "观看历史",
    "Watch later": "稍后观看",
    "Your videos": "你的视频",
    "Your YouTube channel": "你的 YouTube 频道",
    "Last updated": "上次更新",
    "Current log": "当前日志",
    "Clear all logs": "清除全部日志",
    "Delete all log files?": "删除所有日志文件？",
    "This signs you out and clears cached cookies.": "这会退出当前账号并清除缓存的 Cookie。",
    "Wipes stored cookies and the visitor token. The next playback attempt will run anonymously. Use this if playback or sign-in is stuck.": "清除已保存的 Cookie 和访客令牌。下一次播放将以匿名方式运行。播放或登录卡住时可以使用此功能。",
    "Videos download to your device before playback. Lower qualities save space and download faster.": "视频会在播放前下载到设备。较低画质更节省空间，下载也更快。",
    "Sign in to access your watch history, playlists, liked videos, and Watch Later.": "登录后可访问观看历史、播放列表、喜欢的视频和稍后观看。",
    "Playlists you create on YouTube will appear here.": "你在 YouTube 创建的播放列表会显示在这里。",
    "Pull to refresh or sign in to see your home feed.": "下拉刷新，或登录后查看你的首页推荐。",
    "Works with YouTube, Vimeo, X/Twitter, TikTok, SoundCloud, and ~2,000 other sites supported by yt-dlp.": "支持 YouTube、Vimeo、X/Twitter、TikTok、SoundCloud，以及 yt-dlp 支持的约 2,000 个网站。",
    "Tap a video to play — it will be saved here automatically.": "点击视频播放后，它会自动保存在这里。",
    "Reveal in Finder": "在 Finder 中显示",
    "Show in Finder": "在 Finder 中显示",
    "Open": "打开",
    "Play": "播放",
    "Pause": "暂停",
    "Previous": "上一个",
    "Quality": "画质",
    "Audio": "音频",
    "Video quality": "视频画质",
    "Audio only": "仅音频",
    "Download audio": "下载音频",
    "Download video": "下载视频",
    "Cancel download": "取消下载",
    "Failed": "失败",
    "Error": "错误",
    "Try again": "重试",
    "Load more": "加载更多",
    "No results": "没有结果",
    "No comments": "暂无评论",
    "Reply": "回复",
    "Replies": "回复",
    "Like": "赞",
    "Unlike": "取消赞",
    "Share video": "分享视频",
    "Copy": "复制",
    "More": "更多",
    "Playlist": "播放列表",
    "Private": "私密",
    "Public": "公开",
    "Unlisted": "不公开列出",
    "Description": "简介",
    "Views": "观看次数",
    "Subscribers": "订阅者",
    "%@ likes": "%@ 个赞",
    "%@ subscribers": "%@ 位订阅者",
    "%lld subscribers": "%lld 位订阅者",
    "%lld videos": "%lld 个视频",
    "%lld views": "%lld 次观看",
    "%lld selected": "已选择 %lld 项",
    "%lld items": "%lld 项",
    "1 (sequential)": "1（顺序）",
    "Downloading %lld%%": "正在下载 %lld%%",
    "Updated to %@": "已更新至 %@",
    "“%@” will be permanently removed from your device.": "“%@”将从设备中永久删除。",
    "Delete %@?": "删除 %@？",
    "No videos": "暂无视频",
    "No subscriptions": "暂无订阅",
    "No history": "暂无历史记录",
    "No favorites": "暂无收藏",
    "Settings saved": "设置已保存",
    "You need to sign in to do that.": "需要先登录才能执行此操作。",
    "YouTube is rate-limiting requests. Try again in a moment.": "YouTube 正在限制请求频率，请稍后再试。",
    "This video is unavailable.": "此视频不可用。",
    "Your session expired. Please sign in again.": "登录会话已过期，请重新登录。",
    "Network error: %@": "网络错误：%@",
}


def main() -> None:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})

    for source, translated in ZH.items():
        entry = strings.setdefault(source, {})
        localizations = entry.setdefault("localizations", {})
        localizations["zh-Hans"] = {
            "stringUnit": {
                "state": "translated",
                "value": translated,
            }
        }

    CATALOG.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added/updated {len(ZH)} Simplified Chinese strings in {CATALOG}")


if __name__ == "__main__":
    main()
